gdf_file: spec/data/patchelf.gdf
gdfxml_file: spec/data/patchelf.gdf.xml
strace_file: spec/data/patchelf.strace
pkgmap_file: spec/data/patchelf.lift.csv

build_home: /home/shane/src/patchelf-0.8

logfile: bee.log
loglevel: INFO

#beedb: .beedb

loaders:
  - GDFLoader
  - GDFXMLLoader
  - STraceLoader

writer: Neo4jWriter

strace_flatten:
  - g++
  - gcc

junkfiles:
  - makefile
  - makefile.am
  - config.status
  - config.h.in
  - configure
  - configure.ac
  - aclocal.m4
  - .po
  - .plo
